#!/bin/bash

ARGS="--param ../Labs/linef/linef-config.xml"
ARGS+=" --lab ../Labs/linef/linef-lab.xml"
ARGS+=" --grid ../Labs/linef/linef-grid.xml"
ARGS+=" --gps"
#ARGS+=" --scoring 4"

(cd simulator; ./simulator $ARGS) &

sleep 1

(cd Viewer; ./Viewer --autoconnect) &

sleep 2

(cd robsample; ./robsample )

killall Viewer
killall simulator

(cd robsample; octave --eval 'load("output.txt");figure;plot(output(:,1),output(:,2),"-;pos Error;",output(:,1),output(:,3),"o;sensor;",output(:,1),output(:,6),"-;u;");pause')
# (cd robsample; octave --eval 'load("output.txt");figure;plot(output(:,1),output(:,2),"-;pos Error;",output(:,1),output(:,3),"o;sensor reading;");pause')

echo Bye
